### PR TITLE
Mezentsev 563 506 Refactoring: Table component for lists and fixed index

### LINKED ISSUE #506: delete index in components
we need to delete indexes in components mentors, secretaries, students, lessons, groups, courses
This is product owner's wish @so2niko

### LINKED ISSUE #563: Refactoring: Table component for lists
make file for table of list`s with own sorting as validation

### PR DESCRIPTION
**Pull request by D-mezentseff**
Closed #563  
Closed #506 

make file for table of list`s with own sorting as validation
delete indexes in components mentors, secretaries, students, lessons, groups, courses

Video about creating table component with own sorting func

https://user-images.githubusercontent.com/82518924/122241605-5bdfab00-cecb-11eb-9cc7-a8ae8d2f8f03.mp4

Video about deleting index from list and blocks

https://user-images.githubusercontent.com/82518924/122241858-8b8eb300-cecb-11eb-955d-908fd41c8156.mp4

### CODE REVIEW

**Review by anton-sedchenko — APPROVED** [review]

**Review by Keyxnx — APPROVED** [review]

**Review by ViktoriiaKR — APPROVED** [review]

File: src/components/table/table.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+                          data-sorting-param={name}
+                          data-sorted-by-ascending={Number(sortedByAscending)}
+                          onClick={handleSortByParam}
+                          className={classNames({ [styles.rotate]: !sortedByAscending })}
+                        >
+                          {tableHead}
+                        </span>
+            </th>
+          ))}
+          { currentUser && currentUser.role !== 2 ? <th scope="col" className="text-center">Edit</th> : null }
```
Comment (AllaYakymova) [inline src/components/table/table.js:43]: would be better to transmit roles in the prop if you want to make this table universal component. In different lists edit function have users with different roles

**Review by sarhan-azizov — APPROVED** [review]
